package Model.PriceReduction;
// Generated 25-jun-2020 18:32:35 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pricereduction generated by hbm2java
 */
public class Pricereduction  implements java.io.Serializable {


     private int idReduction;
     private Double reducedprice;
     private Date startdate;
     private Date enddate;
     private Set items = new HashSet(0);

    public Pricereduction() {
    }

	
    public Pricereduction(int idReduction) {
        this.idReduction = idReduction;
    }
    public Pricereduction(int idReduction, Double reducedprice, Date startdate, Date enddate, Set items) {
       this.idReduction = idReduction;
       this.reducedprice = reducedprice;
       this.startdate = startdate;
       this.enddate = enddate;
       this.items = items;
    }
   
    public int getIdReduction() {
        return this.idReduction;
    }
    
    public void setIdReduction(int idReduction) {
        this.idReduction = idReduction;
    }
    public Double getReducedprice() {
        return this.reducedprice;
    }
    
    public void setReducedprice(Double reducedprice) {
        this.reducedprice = reducedprice;
    }
    public Date getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }
    public Date getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }




}


