package Model.User;
// Generated 25-jun-2020 18:32:35 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Userlogin generated by hbm2java
 */
public class Userlogin  implements java.io.Serializable {


     private String username;
     private String pass;
     private String type;
     private Set items = new HashSet(0);

    public Userlogin() {
    }

	
    public Userlogin(String username, String pass) {
        this.username = username;
        this.pass = pass;
    }
    public Userlogin(String username, String pass, String type, Set items) {
       this.username = username;
       this.pass = pass;
       this.type = type;
       this.items = items;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set getItems() {
        return this.items;
    }
    
    public void setItems(Set items) {
        this.items = items;
    }

    @Override
    public String toString() {
        return "Userlogin{" + "username=" + username + ", pass=" + pass + ", type=" + type + ", items=" + items + '}';
    }




}


